[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
gas_reports = ["DOVE", "ReflectionMath"]

[profile.fast]
optimizer = false

[profile.test]
verbosity = 4
gas_reports = ["*"]
# Enable fuzzing tests with 1000 runs
fuzz = { runs = 1000 }

[rpc_endpoints]
base = "${BASE_MAINNET_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"

[etherscan]
base = { key = "${BASESCAN_API_KEY}" }
